am7xxx: don't use partial designated initializers
Compilers may warn about missing fields in initializers when more checks
are enabled with STRICT_COMPILATION_CHECKS=ON:

  .../src/am7xxx.c:1131:31: error: missing field 'direction' initializer [-Werror,-Wmissing-field-initializers]
          struct am7xxx_header h = { 0 };
                                       ^
  1 error generated.