am7xxx-play: rename CODEC_FLAG_QSCALE to AV_CODEC_FLAG_QSCALE
In FFMpeg 3.5+ the unprefixed CODEC_* constants have been removed, only
the correspondent AV_CODEC_* ones are available.

This fixes a build failure:

  .../examples/am7xxx-play.c: In function 'video_output_init':
  .../examples/am7xxx-play.c:240:34: error: 'CODEC_FLAG_QSCALE' undeclared (first use in this function); did you mean 'AV_CODEC_FLAG_QSCALE'?
    output_codec_ctx->flags      |= CODEC_FLAG_QSCALE;
                                    ^~~~~~~~~~~~~~~~~
                                    AV_CODEC_FLAG_QSCALE